### ISSUE TITLE
Local testing?

### ISSUE THREAD

**Issue by thewatts** [buttercloud/stripe_tester#5]
I just want to clarify - that in order to use this gem to locally test webhooks, I need to have a version of the app running on `localhost` or something, correct?

Or is it possible to have the `StripeTester.webhook_url` point to a test server?

I tried:

`StripeTester.webhook_url = "http://www.example.com/my_post_url`, where `my_post_url` was the url in my `routes` file - however, it would timeout.

This is why I suspect that the above is necessary - though I'd love to know if I'm doing it wrong! :D

Thanks!

**Comment by deuxshaish** [comment]
I use [ngrok](https://ngrok.com/) to solve this through tunneling request to my local environment. [UltraHook](http://www.ultrahook.com) seems to be another praised solution.

**Comment by luaybs** [comment]
Thanks @deuxshaish,

That's one way to do it, but I think a better solution would be to make this work out of the box.

**Comment by deuxshaish** [comment]
That's the recommended solution by stripe and it's also universal, not only specific to stripe. Establishing a public tunnel to your local environment is necessary in many situations. Ngrok (and other solutions) do make it work out of the box.
