### ISSUE TITLE
template for account.application.deauthorized

### ISSUE THREAD

**Issue by EnotPoloskun** [buttercloud/stripe_tester#7]
Hello. Thanks for your gem, it helps so much.

I haven't found template for account.application.deauthorized event.

Could you please provide an example for this event?
Thanks in advance!

**Comment by luaybs** [comment]
Hello @EnotPoloskun, 

Thanks for pointing that out. I'm currently looking into it at the moment.

**Comment by luaybs** [comment]
Hello @EnotPoloskun,

Sorry for the very late reply, but I couldn't find any reference to `account.application.deauthorized` type of webhook on the Stripe docs or Dasboard.

If you know of any way to get the data, please let me know.
