### ISSUE TITLE
Return a HashWithIndifferentAccess when Rails is detected

### ISSUE THREAD

**Issue by luaybs** [buttercloud/stripe_tester#9]
When Rails is detected, instead of returning a normal `Hash`, `stripe_tester` could return a `HashWithIndifferentAccess` to make it less of a hassle on the user to convert it.

**Comment by afhammad** [comment]
It would also be helpful if when passing in a hash to override/merge attributes they can be passed in as indifferent (i.e support symbols).

**Comment by luaybs** [comment]
Closed #10
